### ISSUE TITLE
FSEventStreamStart error with Powerline

### ISSUE THREAD

**Issue by mhartington** [saghul/pyuv#182]
Started over here: https://github.com/Lokaltog/powerline/issues/1108

Getting this weird error in my terminal when I try to use powerlines VCS segment.

```
2014-10-06 10:47 Python[6256] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

MacOSX: Yosemite 
Python 2.7 from homebrew

It is work noting that the segment does work, but it includes this crazy 2000+ lines of the same error, just repeated over and over.

**Comment by jaspernbrouwer** [comment]
I'm getting a similar error:

```txt
2015-01-21 14:13:08,815:ERROR:shell:branch:Failed to compute tree status: /path/to/a/git/repo: Could not open '/path/to/a/git/repo/.git/config': Too many open files
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/segments/common/vcs.py", line 27, in __call__
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/vcs/__init__.py", line 213, in tree_status
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/vcs/__init__.py", line 203, in __call__
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/vcs/__init__.py", line 193, in cache_and_get
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/vcs/git.py", line 84, in status
  File "/usr/local/lib/python2.7/site-packages/powerline/lib/vcs/git.py", line 141, in do_status
  File "/usr/local/lib/python2.7/site-packages/pygit2/repository.py", line 59, in __init__
OSError: /path/to/a/git/repo: Could not open '/path/to/a/git/repo/.git/config': Too many open files
```

- OS X Yosemite 10.10.1 (14B25)
- Python 2.7.9 (through homebrew)
- libgit2 0.22.1 (through homebrew with custom formula to get this version)
- pygit2 0.22.0 (through pip)
- libuv 1.2.1
- pyuv 1.0.2
- powerline 2.0 (through pip)

```txt
>>> import pyuv
>>> pyuv.LIBUV_VERSION
'1.2.1'
```

**Comment by saghul** [comment]
@jaspernbrouwer That's a different problem. The exception comes from pygit2, not from pyuv. OSX comes with a very small open files limit, check it out with `ulimit -a`.

**Comment by jaspernbrouwer** [comment]
I had a feeling I was reporting this to the wrong repo, pyuv didn't show up in the trace. I guess I was thrown off by Google serving me all sorts of resources pointing to libuv being the source of these issues.

Thanks anyway!

**Comment by saghul** [comment]
No worries!

**Comment by saghul** [comment]
Does anyone still get this?

**Comment by mhartington** [comment]
Havne't used the python version of powerline in a while so can't say for sure.
Last time I tested your fix @saghul is seemed to fix the issue, so I will close this.

**Comment by saghul** [comment]
Thanks Mike!
